### ISSUE TITLE
White Screen after action on Inspect Button

### ISSUE THREAD

**Issue by Taombawkry** [kernel-community/honour#5]
Encountering an issue where selecting the 'Inspect' button to view elements results in a white screen. The console logs multiple errors at this point, which appear to be related to resource loading, application manifest processing, and a critical TypeError in React.

Key errors from the console include:

1. An `[Intervention]` warning suggesting slow network conditions and fallback font usage.
2. A 404 error indicating that a resource (`logo192.png`) failed to load.
3. A manifest fetching error where the browser is unable to process the web app manifest file.
4. A TypeError related to a `null` reference when attempting to access the 'basename' property in `index.tsx`.

![Screenshot 2024-03-30 120141](https://github.com/kernel-community/honour/assets/83420013/2e2bbfd0-b0b1-46ff-8959-ac531c5bb499)

**Comment by gichiba** [comment]
I have this issue sometimes with metamask on firefox, but not with the brave browser wallet (android).

**Comment by andytudhope** [comment]
@Taombawkry can you try replicate this just on https://honour.community rather than the Arweave perma-version, and post your console logs here if you do? That'll help debug.

**Comment by Taombawkry** [comment]
Issue Replication:
Selecting inspect under the actions column after receiving a pledge. 

Result was the same but the error logs read different:
![Screenshot 2024-03-30 130605](https://github.com/kernel-community/honour/assets/83420013/c058c551-f33b-4562-9d92-99908a553a78)
